### PR TITLE
Correctly parse deltat.preds file using new format

### PR DESCRIPTION
**Pull request by reallyasi9**
As of today, seemingly, the published deltat.preds file has changed to include the Julian date.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Thank you for letting me know! I'll try to release a fixed version today.

I'm not sure I can merge this code as-is, though, because thousands of machines will already have a `deltat.preds` on disk that's in the old format — which I think this branch would break? The routine will have to become able to detect the difference between the two formats, I think.

**Comment by brandon-rhodes** [comment]
Thanks again so much for notifying me quickly! I have just released Skyfield 1.10. If you could, test it for me and let me know if it now parses the file correctly. Thanks!

**Comment by zorrolo** [comment]
Hi, it seems like this is relevant for issues I have with my scripts. Unfortunately none of them work anymore and as I tried to execute the simplest example from the skyfield documentation it produces the very same error on my machine.
As I am a student who recently just started to learn python and using skyfield in order to achieve some calculations for planets position and distance to earth I don't really have enough knowledge to help myself.
Could someone please explain (in a beginner friendly way) what exactly to do to avoid this error?

Here is the simplest example that leads to the mentioned error:
`#!/usr/bin/env python
# -*- coding: utf-8 -*-

from skyfield.api import load

planets = load('de431_excerpt2.bsp')
earth, mars = planets['earth'], planets['mars barycenter']

ts = load.timescale()
t = ts.now()
astrometric = earth.at(t).observe(mars)
ra, dec, distance = astrometric.radec()

#print(ra)
#print(dec)
print(distance)`

and this is the error message I receive every time:
`$ python python3-script.py 
Traceback (most recent call last):
  File "python3-script.py", line 9, in <module>
    ts = load.timescale()
  File "/home/user/anaconda3/lib/python3.7/site-packages/skyfield/iokit.py", line 270, in timescale
    preds = self('deltat.preds')
  File "/home/user/anaconda3/lib/python3.7/site-packages/skyfield/iokit.py", line 151, in __call__
    expiration_date, data = parser(f)
  File "/home/user/anaconda3/lib/python3.7/site-packages/skyfield/iokit.py", line 347, in parse_deltat_preds
    expiration_date = date(year[0] + 2, month[0], 1)
ValueError: year 58668 is out of range
`

**Comment by brandon-rhodes** [comment]
@zorrolo If you'll upgrade Skyfield to the latest version, the error should go away — maybe `pip install -U skyfield` will do it?

**Comment by zorrolo** [comment]
@brandon-rhodes Thank you very much! I tried to install skyfield before but what I didn't use was that '-U' parameter. Thankfully it worked when I tried it using your suggestions. Now everything seems to work perfectly fine again!

**Comment by brandon-rhodes** [comment]
Good, I'm glad it's working — enjoy!

**Comment by troyswanson** [comment]
Thanks for this fix!

**Pull request closed without merging**
