### PR TITLE
Test TLE vs XML for similar Position (Issue #394)

### PR DESCRIPTION
**Pull request by glangford**
Test/Evaluation code  - for Stations in stations.txt and the XML equivalent data published by Celestrak, create 'twin' `EarthSatellite` objects using each source and verify that they have a similar position at a set time. For the included TLE and XML files, the positions of all Stations are essentially identical.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
@glangford — Thank you for drafting this Python code! I suspect that it will not only be important to Skyfield users, but to all users of the underlying `sgp4` library for Python that Skyfield uses. Can we move this pull request over to its repository instead?

https://github.com/brandon-rhodes/python-sgp4/

There, it will be able to benefit other projects and not just Skyfield. Thanks!

**Comment by glangford** [comment]
> I suspect that it will not only be important to Skyfield users, but to all users of the underlying sgp4 library for Python that Skyfield uses. Can we move this pull request over to its repository instead?

@brandon-rhodes Yes, I can do that. Please let me know of any suggestions (are you ok with the test files as they are?)

I will keep this pull request open for a while in case there are additional comments.

**Comment by glangford** [comment]
Closing since the code has been moved to the underlying sgp4 library.

**Comment by brandon-rhodes** [comment]
Thanks!

**Pull request closed without merging**
