### PR TITLE
Fix nonexistent attribute in `_KeplerOrbit` object

### PR DESCRIPTION
**Pull request by JoshPaterson**
The `elements_at_epoch` attribute of the `_KeplerOrbit` object is referring to a nonexistent attribute of the `_KeplerOrbit` class, this PR fixes it.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Is there any chance you could write a test that would help us keep this fixed even as other work goes on in the future?

**Comment by JoshPaterson** [comment]
Yes, I will do that!

**Comment by brandon-rhodes** [comment]
@JoshPaterson — Happy Monday! I wanted to check whether you expected to make more progress on this soon, or whether I should myself schedule some time soon to take a look; I didn't want to jump in and run over whatever you were doing, if you have already gotten started on it.

**Comment by JoshPaterson** [comment]
Thanks for your patience! I changed the tests so that all of the orbit checks create a `KeplerOrbit` object and then ask it for its `elements_at_epoch` attribute rather than creating an OsculatingElements object directly. Now the `elements_at_epoch` attribute will get lots of exercise!

**Comment by brandon-rhodes** [comment]
Thanks for integrating this into the tests!

**Pull request merged**
